const form=qs("#clientForm");let selectedTemplate="personal";let editingClient=null;

function showError(msg){console.error(msg);alert(msg?.message||String(msg))}
function setTemplate(t){selectedTemplate=t;qs("#template").value=t;document.querySelectorAll(".template-pick button").forEach(b=>b.classList.toggle("active",b.dataset.template===t));qs("#businessFields").classList.toggle("hidden",t!=="business")}
function clearForm(){editingClient=null;form.reset();qs("#clientId").value="";setTemplate(new URLSearchParams(location.search).get("template")==="business"?"business":"personal");qs("#formTitle").textContent="New Client";qs("#duration").value="30";qs("#customDays").value="";qs("#customDaysWrap").classList.add("hidden");renderSubscriptionFields({subscriptionActive:false,subscriptionStart:null,subscriptionEnd:null})}
function fillForm(c){editingClient=c;["clientId","name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(k=>{if(qs("#"+k))qs("#"+k).value=k==="clientId"?c.id:(c[k]||"")});setTemplate(c.template||"personal");qs("#formTitle").textContent="Edit Client";renderSubscriptionFields(c)}
function renderSubscriptionFields(c){const s=subscriptionState(c);qs("#subscriptionBadge").textContent=s.label;qs("#subscriptionBadge").className="status-badge "+s.status;qs("#subscriptionStart").textContent=c.subscriptionStart?formatDateTime(c.subscriptionStart):"—";qs("#subscriptionEnd").textContent=c.subscriptionEnd?formatDateTime(c.subscriptionEnd):"No expiry";qs("#activateBtn").textContent=s.status==="active"?"Extend / Renew":"Activate"}
function selectedDuration(){const v=qs("#duration").value;if(v==="custom"){const n=Number(qs("#customDays").value);return n>0?n:0}if(v==="none")return 0;return Number(v)}
async function activateCurrent(){if(!editingClient){alert("আগে Client তথ্য Save করুন। তারপর Subscription Activate করুন।");return}const days=selectedDuration();if(qs("#duration").value==="custom"&&!days){alert("Custom Days-এ একটি বৈধ দিন সংখ্যা দিন।");return}try{activateSubscription(editingClient,days);editingClient=await saveClient(editingClient);fillForm(editingClient);await renderList();alert(days?"Subscription activated/renewed.":"Subscription activated with no expiry.")}catch(e){showError(e)}}
async function deactivateCurrent(){if(!editingClient){alert("আগে Client Save করুন।");return}if(!confirm("এই client-এর subscription বন্ধ করবেন?"))return;try{deactivateSubscription(editingClient);editingClient=await saveClient(editingClient);fillForm(editingClient);await renderList();alert("Subscription deactivated.")}catch(e){showError(e)}}
async function renderList(){const box=qs("#clientList");try{const list=await getClients();if(!list.length){box.innerHTML='<div class="empty">এখনো কোনো client তৈরি হয়নি।</div>';return}box.innerHTML=list.map(c=>{const s=subscriptionState(c);return '<div class="client-item"><div><strong>'+esc(c.name)+'</strong><br><small>'+(c.template==="business"?"Personal + Business":"Personal")+(c.company?" • "+esc(c.company):"")+'</small><div class="list-sub"><span class="status-badge '+s.status+'">'+esc(s.label)+'</span><span>Expiry: '+esc(c.subscriptionEnd?formatDate(c.subscriptionEnd):"No expiry")+'</span></div></div><div class="client-actions"><a class="mini" href="'+cardUrl(c.id)+'" target="_blank">View</a><button class="mini" onclick="editClient(\''+c.id+'\')">Edit</button><button class="mini sub" onclick="quickActivate(\''+c.id+'\')">Activate</button><button class="mini warn" onclick="quickDeactivate(\''+c.id+'\')">Off</button><button class="mini danger" onclick="deleteClient(\''+c.id+'\')">Delete</button></div></div>'}).join("")}catch(e){box.innerHTML='<div class="empty">Client list load করতে সমস্যা হয়েছে।</div>';console.error(e)}}
async function editClient(id){try{const c=await getClient(id);if(c){fillForm(c);scrollTo({top:0,behavior:"smooth"})}}catch(e){showError(e)}}
async function quickActivate(id){try{const c=await getClient(id);if(!c)return;const raw=prompt("কত দিনের subscription দেবেন?\nউদাহরণ: 30, 365, 1825\n0 = No Expiry","30");if(raw===null)return;const days=Number(raw);if(!Number.isFinite(days)||days<0){alert("সঠিক দিন সংখ্যা দিন।");return}activateSubscription(c,days);await saveClient(c);if(editingClient&&editingClient.id===id){editingClient=c;fillForm(c)}await renderList()}catch(e){showError(e)}}
async function quickDeactivate(id){try{const c=await getClient(id);if(!c)return;if(!confirm("Subscription বন্ধ করবেন?"))return;deactivateSubscription(c);await saveClient(c);if(editingClient&&editingClient.id===id){editingClient=c;fillForm(c)}await renderList()}catch(e){showError(e)}}
async function deleteClient(id){if(!confirm("এই client delete করবেন?"))return;try{await removeClient(id);await renderList();if(qs("#clientId").value===id)clearForm()}catch(e){showError(e)}}

form&&form.addEventListener("submit",async e=>{e.preventDefault();const data=editingClient||{id:null,template:selectedTemplate,subscriptionActive:false,subscriptionStart:null,subscriptionEnd:null};data.template=selectedTemplate;["name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(k=>data[k]=qs("#"+k).value.trim());try{editingClient=await saveClient(data);fillForm(editingClient);await renderList();alert("Client saved successfully. Subscription can now be activated from the panel.")}catch(e){showError(e)}});

async function initAdmin(){
 const {data:{session}}=await supabaseClient.auth.getSession();
 if(!session){showLogin();return}
 const {data:claimData,error:claimError}=await supabaseClient.rpc("claim_first_admin");
 if(claimError)console.warn("Admin claim check:",claimError);
 const {data:admin,error}=await supabaseClient.from("admin_users").select("user_id,email").eq("user_id",session.user.id).maybeSingle();
 if(error||!admin){showLogin("এই account-টি Admin হিসেবে অনুমোদিত নয়।");await supabaseClient.auth.signOut();return}
 showAdmin();clearForm();await renderList();
}
function showLogin(message=""){qs("#loginPanel").classList.remove("hidden");qs("#adminApp").classList.add("hidden");qs("#logoutBtn").classList.add("hidden");if(message)qs("#loginMessage").textContent=message}
function showAdmin(){qs("#loginPanel").classList.add("hidden");qs("#adminApp").classList.remove("hidden");qs("#logoutBtn").classList.remove("hidden")}
qs("#loginForm").addEventListener("submit",async e=>{e.preventDefault();qs("#loginMessage").textContent="Signing in...";const {error}=await supabaseClient.auth.signInWithPassword({email:qs("#loginEmail").value.trim(),password:qs("#loginPassword").value});if(error){qs("#loginMessage").textContent=error.message;return}await initAdmin()});
qs("#logoutBtn").addEventListener("click",async()=>{await supabaseClient.auth.signOut();location.reload()});
document.querySelectorAll(".template-pick button").forEach(b=>b.addEventListener("click",()=>setTemplate(b.dataset.template)));
qs("#duration").addEventListener("change",function(){qs("#customDaysWrap").classList.toggle("hidden",this.value!=="custom")});
qs("#activateBtn").addEventListener("click",activateCurrent);qs("#deactivateBtn").addEventListener("click",deactivateCurrent);qs("#resetBtn").addEventListener("click",clearForm);
initAdmin();