const form=qs("#clientForm");var selectedTemplate="personal";
function setTemplate(t){selectedTemplate=t;qs("#template").value=t;document.querySelectorAll(".template-pick button").forEach(function(b){b.classList.toggle("active",b.dataset.template===t)});qs("#businessFields").classList.toggle("hidden",t!=="business")}
function clearForm(){form.reset();qs("#clientId").value="";setTemplate(new URLSearchParams(location.search).get("template")==="business"?"business":"personal");qs("#formTitle").textContent="New Client"}
function fillForm(c){["clientId","name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(function(k){if(qs("#"+k))qs("#"+k).value=c[k]||""});setTemplate(c.template||"personal");qs("#formTitle").textContent="Edit Client"}
function renderList(){var box=qs("#clientList"),list=getClients();if(!list.length){box.innerHTML='<div class="empty">এখনো কোনো client তৈরি হয়নি।</div>';return}box.innerHTML=list.map(function(c){return'<div class="client-item"><div><strong>'+esc(c.name)+'</strong><br><small>'+(c.template==="business"?"Personal + Business":"Personal")+(c.company?" • "+esc(c.company):"")+'</small></div><div class="client-actions"><a class="mini" href="'+cardUrl(c.id)+'" target="_blank">View</a><button class="mini" onclick="editClient(\''+c.id+'\')">Edit</button><button class="mini danger" onclick="deleteClient(\''+c.id+'\')">Delete</button></div></div>'}).join("")}
function editClient(id){var c=getClient(id);if(c){fillForm(c);scrollTo({top:0,behavior:"smooth"})}}
function deleteClient(id){if(!confirm("এই client delete করবেন?"))return;saveClients(getClients().filter(function(c){return c.id!==id}));renderList();if(qs("#clientId").value===id)clearForm()}
form&&form.addEventListener("submit",function(e){e.preventDefault();var old=getClients(),id=qs("#clientId").value||Date.now().toString(36),data={id:id,template:selectedTemplate};["name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(function(k){data[k]=qs("#"+k).value.trim()});var next=old.some(function(x){return x.id===id})?old.map(function(x){return x.id===id?data:x}):[data].concat(old);saveClients(next);fillForm(data);renderList();alert("Client saved successfully.")});
document.querySelectorAll(".template-pick button").forEach(function(b){b.addEventListener("click",function(){setTemplate(b.dataset.template)})});
qs("#resetBtn")&&qs("#resetBtn").addEventListener("click",clearForm);
var editId=new URLSearchParams(location.search).get("edit");if(editId&&getClient(editId))fillForm(getClient(editId));else clearForm();renderList();