const form=qs("#clientForm");var selectedTemplate="personal";var editingClient=null;
function setTemplate(t){selectedTemplate=t;qs("#template").value=t;document.querySelectorAll(".template-pick button").forEach(function(b){b.classList.toggle("active",b.dataset.template===t)});qs("#businessFields").classList.toggle("hidden",t!=="business")}
function clearForm(){editingClient=null;form.reset();qs("#clientId").value="";setTemplate(new URLSearchParams(location.search).get("template")==="business"?"business":"personal");qs("#formTitle").textContent="New Client";qs("#duration").value="30";qs("#customDays").value="";qs("#customDaysWrap").classList.add("hidden");renderSubscriptionFields({subscriptionActive:false,subscriptionStart:null,subscriptionEnd:null})}
function fillForm(c){editingClient=c;["clientId","name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(function(k){if(qs("#"+k))qs("#"+k).value=c[k]||""});setTemplate(c.template||"personal");qs("#formTitle").textContent="Edit Client";renderSubscriptionFields(c)}
function renderSubscriptionFields(c){var s=subscriptionState(c);qs("#subscriptionBadge").textContent=s.label;qs("#subscriptionBadge").className="status-badge "+s.status;qs("#subscriptionStart").textContent=c.subscriptionStart?formatDateTime(c.subscriptionStart):"—";qs("#subscriptionEnd").textContent=c.subscriptionEnd?formatDateTime(c.subscriptionEnd):"No expiry";qs("#activateBtn").textContent=s.status==="active"?"Extend / Renew":"Activate"}
function selectedDuration(){var v=qs("#duration").value;if(v==="custom"){var n=Number(qs("#customDays").value);return n>0?n:0}if(v==="none")return 0;return Number(v)}
function activateCurrent(){var c=editingClient;if(!c){alert("আগে Client তথ্য Save করুন। তারপর Subscription Activate করুন।");return}var days=selectedDuration();if(qs("#duration").value==="custom"&&!days){alert("Custom Days-এ একটি বৈধ দিন সংখ্যা দিন।");return}activateSubscription(c,days);saveClients(getClients().map(function(x){return x.id===c.id?c:x}));renderSubscriptionFields(c);renderList();alert(days?"Subscription activated/renewed.":"Subscription activated with no expiry.")}
function deactivateCurrent(){var c=editingClient;if(!c){alert("আগে Client Save করুন।");return}if(!confirm("এই client-এর subscription বন্ধ করবেন?"))return;deactivateSubscription(c);saveClients(getClients().map(function(x){return x.id===c.id?c:x}));renderSubscriptionFields(c);renderList();alert("Subscription deactivated.")}
function renderList(){var box=qs("#clientList"),list=getClients();if(!list.length){box.innerHTML='<div class="empty">এখনো কোনো client তৈরি হয়নি।</div>';return}box.innerHTML=list.map(function(c){var s=subscriptionState(c);return'<div class="client-item"><div><strong>'+esc(c.name)+'</strong><br><small>'+(c.template==="business"?"Personal + Business":"Personal")+(c.company?" • "+esc(c.company):"")+'</small><div class="list-sub"><span class="status-badge '+s.status+'">'+esc(s.label)+'</span><span>Expiry: '+esc(c.subscriptionEnd?formatDate(c.subscriptionEnd):"No expiry")+'</span></div></div><div class="client-actions"><a class="mini" href="'+cardUrl(c.id)+'" target="_blank">View</a><button class="mini" onclick="editClient(\''+c.id+'\')">Edit</button><button class="mini sub" onclick="quickActivate(\''+c.id+'\')">Activate</button><button class="mini warn" onclick="quickDeactivate(\''+c.id+'\')">Off</button><button class="mini danger" onclick="deleteClient(\''+c.id+'\')">Delete</button></div></div>'}).join("")}
function editClient(id){var c=getClient(id);if(c){fillForm(c);scrollTo({top:0,behavior:"smooth"})}}
function quickActivate(id){var c=getClient(id);if(!c)return;var raw=prompt("কত দিনের subscription দেবেন?\nউদাহরণ: 30, 365, 1825\n0 = No Expiry","30");if(raw===null)return;var days=Number(raw);if(!Number.isFinite(days)||days<0){alert("সঠিক দিন সংখ্যা দিন।");return}activateSubscription(c,days);saveClients(getClients().map(function(x){return x.id===id?c:x}));if(editingClient&&editingClient.id===id)renderSubscriptionFields(c);renderList()}
function quickDeactivate(id){var c=getClient(id);if(!c)return;if(!confirm("Subscription বন্ধ করবেন?"))return;deactivateSubscription(c);saveClients(getClients().map(function(x){return x.id===id?c:x}));if(editingClient&&editingClient.id===id)renderSubscriptionFields(c);renderList()}
function deleteClient(id){if(!confirm("এই client delete করবেন?"))return;saveClients(getClients().filter(function(c){return c.id!==id}));renderList();if(qs("#clientId").value===id)clearForm()}
form&&form.addEventListener("submit",function(e){e.preventDefault();var old=getClients(),id=qs("#clientId").value||Date.now().toString(36),existing=getClient(id),data=existing||{id:id,template:selectedTemplate,subscriptionActive:false,subscriptionStart:null,subscriptionEnd:null};data.template=selectedTemplate;["name","designation","phone","whatsapp","email","location","bio","company","tagline","services","photo","cover","facebook","instagram","linkedin","youtube"].forEach(function(k){data[k]=qs("#"+k).value.trim()});var next=old.some(function(x){return x.id===id})?old.map(function(x){return x.id===id?data:x}):[data].concat(old);saveClients(next);fillForm(data);renderList();alert("Client saved successfully. Subscription can now be activated from the panel.")});
document.querySelectorAll(".template-pick button").forEach(function(b){b.addEventListener("click",function(){setTemplate(b.dataset.template)})});
qs("#duration").addEventListener("change",function(){qs("#customDaysWrap").classList.toggle("hidden",this.value!=="custom")});
qs("#activateBtn").addEventListener("click",activateCurrent);qs("#deactivateBtn").addEventListener("click",deactivateCurrent);qs("#resetBtn")&&qs("#resetBtn").addEventListener("click",clearForm);
var editId=new URLSearchParams(location.search).get("edit");if(editId&&getClient(editId))fillForm(getClient(editId));else clearForm();renderList();