const STORE_KEY="kds_client_cards_v1";
function getClients(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||"[]")}catch(e){return[]}}
function saveClients(list){localStorage.setItem(STORE_KEY,JSON.stringify(list))}
function esc(v){return String(v||"").replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])})}
function qs(s){return document.querySelector(s)}
function slugify(v){return String(v||"client").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50)||"client"}
function getClient(id){return getClients().find(function(x){return x.id===id})}
function cardUrl(id){return "card.html?id="+encodeURIComponent(id)}
function vcard(c){var lines=["BEGIN:VCARD","VERSION:3.0","FN:"+c.name];if(c.phone)lines.push("TEL;TYPE=CELL:"+c.phone);if(c.email)lines.push("EMAIL:"+c.email);if(c.company)lines.push("ORG:"+c.company);if(c.designation)lines.push("TITLE:"+c.designation);if(c.location)lines.push("ADR:;;"+c.location);var urls=[c.facebook,c.instagram,c.linkedin,c.youtube].filter(Boolean);if(urls.length)lines.push("NOTE:"+urls.join(" | "));lines.push("END:VCARD");return lines.join("\n")}
function downloadContact(c){var blob=new Blob([vcard(c)],{type:"text/vcard;charset=utf-8"});var a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=slugify(c.name)+".vcf";a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function renderCard(){var root=qs("#cardRoot");if(!root)return;var id=new URLSearchParams(location.search).get("id");var c=getClient(id);if(!c){root.innerHTML='<div class="empty">Client card পাওয়া যায়নি।<br><a href="admin.html">Client Management</a></div>';return}document.title=c.name+" • Digital Card";var cover=c.cover?'background-image:url("'+esc(c.cover)+'")':"";var photo=c.photo||"https://ui-avatars.com/api/?name="+encodeURIComponent(c.name)+"&background=e8eef8&color=155eef&size=300";var socials=[["Facebook",c.facebook],["Instagram",c.instagram],["LinkedIn",c.linkedin],["YouTube",c.youtube]].filter(function(x){return x[1]});var services=(c.services||"").split(",").map(function(x){return x.trim()}).filter(Boolean);var html='<article class="card-shell"><div class="cover" style="'+cover+'"></div><div class="profile"><img class="avatar" src="'+esc(photo)+'" alt="'+esc(c.name)+'"><div class="identity"><h1>'+esc(c.name)+'</h1><div class="role">'+esc(c.designation)+'</div>'+(c.company?'<div class="company">'+esc(c.company)+'</div>':"")+'</div>'+(c.bio?'<p class="bio">'+esc(c.bio)+'</p>':"")+'<div class="contact-grid">'+(c.phone?'<a class="contact" href="tel:'+esc(c.phone)+'">📞 Call</a>':"")+(c.whatsapp?'<a class="contact" target="_blank" rel="noopener" href="https://wa.me/88'+esc(c.whatsapp.replace(/\D/g,""))+'">💬 WhatsApp</a>':"")+(c.email?'<a class="contact" href="mailto:'+esc(c.email)+'">✉️ Email</a>':"")+(c.location?'<div class="contact">📍 '+esc(c.location)+'</div>':"")+'</div>'+(c.tagline?'<div class="section"><h3>'+esc(c.tagline)+'</h3></div>':"")+(services.length?'<div class="section"><h3>Services</h3><div class="services">'+services.map(function(s){return'<span class="service">'+esc(s)+'</span>'}).join("")+'</div></div>':"")+(socials.length?'<div class="section"><h3>Social</h3><div class="socials">'+socials.map(function(s){return'<a class="social" target="_blank" rel="noopener" href="'+esc(s[1])+'">'+esc(s[0])+'</a>'}).join("")+'</div></div>':"")+'<div class="card-actions"><button class="btn primary" id="saveContact">Save Contact</button><button class="btn secondary" id="shareCard">Share Card</button></div></div></article>';root.innerHTML=html;qs("#saveContact").onclick=function(){downloadContact(c)};qs("#shareCard").onclick=async function(){try{if(navigator.share)await navigator.share({title:c.name,text:"Digital Card",url:location.href});else throw new Error()}catch(e){if(navigator.clipboard)await navigator.clipboard.writeText(location.href);alert("Card link copied.")}}}